version: '3'
services:
  php:
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./src/:/srv/www/
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini-production:/usr/local/etc/php/php.ini
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    

  nginx:
    image: nginx:1.18.0
    ports:
      - 9898:80
    volumes:
      - ./src/:/srv/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - php

  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    depends_on:
      - php
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}